{% set version = "2.10.5" %}

package:
  name: coincbc
  version: {{ version }}

source:
  fn: Cbc-{{ version }}.tgz
  url: http://www.coin-or.org/download/source/Cbc/Cbc-{{ version }}.tgz
  sha256: da1a945648679b21ba56b454b81e939451dc7951d9beb3c3e14f18f64dde6972

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('coincbc', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - pkg-config
  host:
    - libblas
    - libcblas
    - liblapack

test:
  commands:
    - test -f "${PREFIX}/lib/libCbc${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/libCbcSolver${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/libCgl${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/libClp${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/libClpSolver${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/libCoinUtils${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/libOsi${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/libOsiCbc${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/libOsiClp${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/libOsiCommonTests${SHLIB_EXT}"

about:
  home: http://www.coin-or.org/
  license: Eclipse v1.0
  summary: Cbc (Coin-or branch and cut) is an open-source mixed integer programming solver written in C++.

extra:
  recipe-maintainers:
    - scopatz
    - gidden
    - whart222
