{% set version = "2.9.9" %}
{% if linux %}
    {% set libext = ".so" %}
{% else %}
    {% set libext = ".dylib" %}
{% endif %}

{% set variant = "openblas" %}


package:
  name: coincbc
  version: {{ version }}

source:
  fn: Cbc-{{ version }}.tgz
  url: http://www.coin-or.org/download/source/Cbc/Cbc-{{ version }}.tgz
  sha256: aa8404e49b25853b30ebd6291e3beedc9b5f583e3c0c36822fae17507feb0af1

build:
  number: 3
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain
    - gcc
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
  run:
    - libgcc
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*

test:
  commands:
    - test -f "${PREFIX}/lib/libCbc{{ libext }}"
    - test -f "${PREFIX}/lib/libCbcSolver{{ libext }}"
    - test -f "${PREFIX}/lib/libCgl{{ libext }}"
    - test -f "${PREFIX}/lib/libClp{{ libext }}"
    - test -f "${PREFIX}/lib/libClpSolver{{ libext }}"
    - test -f "${PREFIX}/lib/libCoinUtils{{ libext }}"
    - test -f "${PREFIX}/lib/libOsi{{ libext }}"
    - test -f "${PREFIX}/lib/libOsiCbc{{ libext }}"
    - test -f "${PREFIX}/lib/libOsiClp{{ libext }}"
    - test -f "${PREFIX}/lib/libOsiCommonTests{{ libext }}"

about:
  home: http://www.coin-or.org/
  license: Eclipse v1.0
  summary: "Cbc (Coin-or branch and cut) is an open-source mixed integer programming solver written in C++."

extra:
  recipe-maintainers:
    - scopatz
    - gidden
    - whart222
    - jjhelmus
